server:
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: root
mybatis:
  mapper-locations: classpath:com/wzh/mapper/*Mapper.xml
  type-aliases-package: com.wzh.ems.entity
logging:
  level:
    root: info
    com.wzh.dao: debug